name: Build and Publish to npm

on:
  workflow_dispatch:
  push:
    tags:
      - "v*" # Run only when you push a tag like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          always-auth: true

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Debug npm auth & version
        run: |
          echo "Version to publish: $(node -p "require('./package.json').version")"
          npm config list
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Debug npm auth & version
        run: |
          echo "Version to publish: $(node -p "require('./package.json').version")"
          npm config list
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
